version: '3.7'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf  # Configuração do NGINX
      - ./index.php:/usr/share/nginx/html/index.php  # Código PHP na raiz
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    build: ./docker/php  # Caminho para a imagem personalizada PHP
    volumes:
      - ./index.php:/var/www/html/index.php  # Código PHP na raiz
